M48
; DRILL file {KiCad 7.0.9-7.0.9~ubuntu20.04.1} date Fri 05 Jan 2024 14:18:15 GMT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-05T14:18:15+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9-7.0.9~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1693
%
G90
G05
T1
X0.7Y-0.85
X0.7Y-2.4
X2.4Y-0.85
X2.4Y-2.4
T0
M30
